// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoBuffDef.proto

#ifndef PROTOBUF_protoBuffDef_2eproto__INCLUDED
#define PROTOBUF_protoBuffDef_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class detection;
class detectionDefaultTypeInternal;
extern detectionDefaultTypeInternal _detection_default_instance_;

namespace protobuf_protoBuffDef_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_protoBuffDef_2eproto

// ===================================================================

class detection : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:detection) */ {
 public:
  detection();
  virtual ~detection();

  detection(const detection& from);

  inline detection& operator=(const detection& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const detection& default_instance();

  static inline const detection* internal_default_instance() {
    return reinterpret_cast<const detection*>(
               &_detection_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(detection* other);

  // implements Message ----------------------------------------------

  inline detection* New() const PROTOBUF_FINAL { return New(NULL); }

  detection* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const detection& from);
  void MergeFrom(const detection& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(detection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 msgId = 1;
  bool has_msgid() const;
  void clear_msgid();
  static const int kMsgIdFieldNumber = 1;
  ::google::protobuf::int32 msgid() const;
  void set_msgid(::google::protobuf::int32 value);

  // required int32 fftSize = 2;
  bool has_fftsize() const;
  void clear_fftsize();
  static const int kFftSizeFieldNumber = 2;
  ::google::protobuf::int32 fftsize() const;
  void set_fftsize(::google::protobuf::int32 value);

  // optional double power = 4;
  bool has_power() const;
  void clear_power();
  static const int kPowerFieldNumber = 4;
  double power() const;
  void set_power(double value);

  // optional uint64 freqHz = 5;
  bool has_freqhz() const;
  void clear_freqhz();
  static const int kFreqHzFieldNumber = 5;
  ::google::protobuf::uint64 freqhz() const;
  void set_freqhz(::google::protobuf::uint64 value);

  // optional uint64 time = 6;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 6;
  ::google::protobuf::uint64 time() const;
  void set_time(::google::protobuf::uint64 value);

  // optional int32 startBin = 3;
  bool has_startbin() const;
  void clear_startbin();
  static const int kStartBinFieldNumber = 3;
  ::google::protobuf::int32 startbin() const;
  void set_startbin(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:detection)
 private:
  void set_has_msgid();
  void clear_has_msgid();
  void set_has_fftsize();
  void clear_has_fftsize();
  void set_has_startbin();
  void clear_has_startbin();
  void set_has_power();
  void clear_has_power();
  void set_has_freqhz();
  void clear_has_freqhz();
  void set_has_time();
  void clear_has_time();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 msgid_;
  ::google::protobuf::int32 fftsize_;
  double power_;
  ::google::protobuf::uint64 freqhz_;
  ::google::protobuf::uint64 time_;
  ::google::protobuf::int32 startbin_;
  friend struct protobuf_protoBuffDef_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// detection

// required int32 msgId = 1;
inline bool detection::has_msgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void detection::set_has_msgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void detection::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void detection::clear_msgid() {
  msgid_ = 0;
  clear_has_msgid();
}
inline ::google::protobuf::int32 detection::msgid() const {
  // @@protoc_insertion_point(field_get:detection.msgId)
  return msgid_;
}
inline void detection::set_msgid(::google::protobuf::int32 value) {
  set_has_msgid();
  msgid_ = value;
  // @@protoc_insertion_point(field_set:detection.msgId)
}

// required int32 fftSize = 2;
inline bool detection::has_fftsize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void detection::set_has_fftsize() {
  _has_bits_[0] |= 0x00000002u;
}
inline void detection::clear_has_fftsize() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void detection::clear_fftsize() {
  fftsize_ = 0;
  clear_has_fftsize();
}
inline ::google::protobuf::int32 detection::fftsize() const {
  // @@protoc_insertion_point(field_get:detection.fftSize)
  return fftsize_;
}
inline void detection::set_fftsize(::google::protobuf::int32 value) {
  set_has_fftsize();
  fftsize_ = value;
  // @@protoc_insertion_point(field_set:detection.fftSize)
}

// optional int32 startBin = 3;
inline bool detection::has_startbin() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void detection::set_has_startbin() {
  _has_bits_[0] |= 0x00000020u;
}
inline void detection::clear_has_startbin() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void detection::clear_startbin() {
  startbin_ = 0;
  clear_has_startbin();
}
inline ::google::protobuf::int32 detection::startbin() const {
  // @@protoc_insertion_point(field_get:detection.startBin)
  return startbin_;
}
inline void detection::set_startbin(::google::protobuf::int32 value) {
  set_has_startbin();
  startbin_ = value;
  // @@protoc_insertion_point(field_set:detection.startBin)
}

// optional double power = 4;
inline bool detection::has_power() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void detection::set_has_power() {
  _has_bits_[0] |= 0x00000004u;
}
inline void detection::clear_has_power() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void detection::clear_power() {
  power_ = 0;
  clear_has_power();
}
inline double detection::power() const {
  // @@protoc_insertion_point(field_get:detection.power)
  return power_;
}
inline void detection::set_power(double value) {
  set_has_power();
  power_ = value;
  // @@protoc_insertion_point(field_set:detection.power)
}

// optional uint64 freqHz = 5;
inline bool detection::has_freqhz() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void detection::set_has_freqhz() {
  _has_bits_[0] |= 0x00000008u;
}
inline void detection::clear_has_freqhz() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void detection::clear_freqhz() {
  freqhz_ = GOOGLE_ULONGLONG(0);
  clear_has_freqhz();
}
inline ::google::protobuf::uint64 detection::freqhz() const {
  // @@protoc_insertion_point(field_get:detection.freqHz)
  return freqhz_;
}
inline void detection::set_freqhz(::google::protobuf::uint64 value) {
  set_has_freqhz();
  freqhz_ = value;
  // @@protoc_insertion_point(field_set:detection.freqHz)
}

// optional uint64 time = 6;
inline bool detection::has_time() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void detection::set_has_time() {
  _has_bits_[0] |= 0x00000010u;
}
inline void detection::clear_has_time() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void detection::clear_time() {
  time_ = GOOGLE_ULONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::uint64 detection::time() const {
  // @@protoc_insertion_point(field_get:detection.time)
  return time_;
}
inline void detection::set_time(::google::protobuf::uint64 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:detection.time)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protoBuffDef_2eproto__INCLUDED
